services:
  app:
    build: .
    container_name: ticketflow-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
    depends_on:
      mongodb:
        condition: service_started
    restart: unless-stopped
    networks:
      - ticketflow

  mongodb:
    image: mongodb/mongodb-community-server:8.0.4-ubuntu2204
    container_name: ticketflow-mongodb
    restart: unless-stopped
    volumes:
      - mongodb.data:/data/db
      - mongodb.config:/data/configdb
    ports:
      - "27017:27017"
    # environment:
    #   MONGODB_INITDB_ROOT_USERNAME: ${MONGODB__DATABASE_USERNAME}
    #   MONGODB_INITDB_ROOT_PASSWORD: ${MONGODB__DATABASE_PASSWORD}
    networks:
      - ticketflow

  mailhog:
    image: mailhog/mailhog:latest
    container_name: ticketflow-mailhog
    ports:
      - "1025:1025"   # SMTP (para containers)
      - "8025:8025"   # UI Web (acesse em http://localhost:8025)
    restart: unless-stopped
    networks:
      - ticketflow

  email-notifier:
    build: ./services/email-notifier
    container_name: ticketflow-email-notifier
    ports:
      - "8001:8001"
    environment:
      - SMTP_HOST=mailhog
      - SMTP_PORT=1025
      - FROM_EMAIL=ticketflow@demo.local
      - NOTIFY_EMAIL=admin@demo.local
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
      - MAIN_API_URL=http://app:8000
      - SELF_URL=http://email-notifier:8001/webhook
      - RETRY_DELAY=3
      - MAX_RETRIES=20
    depends_on:
      - app
      - mailhog
    restart: unless-stopped
    networks:
      - ticketflow

volumes:
  mongodb.data:
  mongodb.config:

networks:
  ticketflow:
    name: "ticketflow"
    driver: bridge
    attachable: true
    driver_opts:
      com.docker.network.bridge.name: ticketflow
      com.docker.network.bridge.enable_ip_masquerade: "true"
    ipam:
      driver: default
      config:
        - subnet: "12.199.0.0/16"
          gateway: "12.199.0.1"
